### ISSUE TITLE
Thoughts re: AGPL3 or LGPL3

### ISSUE THREAD

**Issue by JamesParrott** [rafmod/nameutils#1]
This is a brilliant library!  Many thanks for creating it.  I've been searching the internet for the past hour or two for a tool to determine given names or forenames, and this is by far the best. 

Anyway, I'd like to release a small tool under the MIT license.  I'd to use nameutils in it as a dependency.  I'm not wedded to the MIT license, I just use it by default, and give it no further thought.  

So I just thought I'd ask what the developers' thoughts were, about making nameutils available under the LGPL3 (so that tools of mine or anyone elses that dynamically link to it, as a normal dependency via PyPi, aren't forced themselves to re-license under GPL3 by the 'viral' clause)?

Alternatively, if full GPL requirements are indeed the intent, I would advise switching to Affero-GPL3 to cover the closed source cloud service loop hole.

**Comment by rafmod** [comment]
Hi! Thanks for the kind words. I wrote something like it for work years ago (identifying names when importing spreadsheets, and producing reports that contained names). Being able to override the code with exceptions when the code gets it wrong is probably the best feature. I really thought it was worth publishing, but when I got around to it I realised it could be so much better (thanks to Unicode). The published version supports names from many more languages and scripts.

I don't want to use the LGPL. I don't think GPL is a virus. I think it's more like a vaccine. :-) My main reason to use GPL is to give both programmers and end-users all the rights they need to control their own computers. The main reason to use MIT (or LGPL) is to only give programmers the rights they need, without concern for the end-users. I don't like the idea of giving rights to programmers who can then withhold those same rights from their users. I can understand why companies like non-GPL licenses but that's not my concern.

If you only chose MIT by default, perhaps you could consider using GPL instead.

I think that you are probably right about using AGPL, and I'll think about it, but for the moment, I'll leave it as is.

**Comment by JamesParrott** [comment]
No problem.  I've used AGPL.  Thanks again - it makes addressing people by their preferred name much easier, including when their surname is written first.
